---
title: "Orvac Simulation Results"
author: "Mark Jones"
date: "`r Sys.time()`"
output:
  html_document:
    classoption: portrait
    number_sections: yes
    self_contained: yes
    theme: united
  pdf_document:
    fig_caption: yes
    number_sections: yes
    toc: yes
    toc_depth: 3
  word_document:
    toc: yes
    toc_depth: '3'
geometry: left=0.2cm,right=0.2cm,top=1cm,bottom=1cm
editor_options:
  chunk_output_type: console
classoption: landscape
---

<!-- css: style.css -->

<!--    toc: yes
    toc_float: true -->

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
# rmarkdown::render("simulation_report.Rmd", clean=TRUE)
knitr::opts_chunk$set(echo = TRUE, fig.path = 'figs/')
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(knitr))
suppressPackageStartupMessages(library(kableExtra))
suppressPackageStartupMessages(library(psych))
suppressPackageStartupMessages(library(grid))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(htmltools))
suppressPackageStartupMessages(library(orvacsim))
#source("util.R")



ggplot2::theme_set(ggplot2::theme_bw())
ggplot2::theme_update(text = element_text(size = 10))
ggplot2::theme_update(legend.position = "top")
# ggplot2::theme_update(legend.title = element_blank())
ggplot2::theme_update(axis.text.x = element_text(size = 10))
ggplot2::theme_update(axis.text.y = element_text(size = 10))

# Work|Right|Fast
# rmarkdown::render("simulation_report.Rmd", clean=TRUE)
```


# Preamble

Quick html table of results.


```{r, echo = F}
mywarnings <- list()

post_final_thresh <- 0

resfiles <- list.files("out", pattern = "*.RDS")

df_all <- data.frame(stringsAsFactors = F)
df_fig1 <- data.frame(stringsAsFactors = F)
df_res_all <- data.frame(stringsAsFactors = F)

mysim <- 1
# fname = resfiles[1]
for(fname in resfiles){
  d1 <- readRDS(file.path(getwd(), "out", fname))
  # d1 <- readRDS(file.path(getwd(), "out", resfiles[1]))

  df_res <- as.data.frame(d1$results)

  nsim <- d1$cfg$n_sims
  # true values for median surv (mnth)
  baseclin <- d1$cfg$ctl_med_tte
  trtclin <- d1$cfg$trt_med_tte
  # true values for seroconversion prob
  basesero <- d1$cfg$baseline_prob_sero
  trtsero <- d1$cfg$trt_prob_sero
  # accrual
  accrual <- d1$cfg$accrual
  info_delay <- d1$cfg$sero_info_delay
  
  # thresholds
  post_final_thresh <- d1$cfg$thresh_p_sup
  
  # what decisions were made at interims?
  intrm_dec_labs <- c("Fut", "ES", "SV", "ND")
  df_res$interim_outcome <- NA
  df_res$interim_outcome <- ifelse(df_res$stop_i_fut == 1 | 
                                     df_res$stop_c_fut == 1, 1, df_res$interim_outcome)
  df_res$interim_outcome <- ifelse(df_res$stop_c_sup == 1, 2, df_res$interim_outcome)
  df_res$interim_outcome <- ifelse(df_res$stop_v_samp == 1, 3, df_res$interim_outcome)
  # in all other cases we made no decision
  df_res$interim_outcome <- ifelse(is.na(df_res$interim_outcome), 4, df_res$interim_outcome)
  df_res$interim_outcome <- factor(df_res$interim_outcome, 
                                   levels = 1:4, 
                                   labels = intrm_dec_labs)
  prob <- prop.table(table(df_res$interim_outcome))
  
  # prob of successful trials at final
  probimmi <- sum(df_res$i_final[df_res$i_final == 1])/nrow(df_res)
  probclin <- sum(df_res$c_final[df_res$c_final == 1])/nrow(df_res)
  
  # sample size
  df_ss_enrlld <- df_res %>% 
    dplyr::summarise(ss_mean = mean(n_enrolled), 
                     ss_sd = sd(n_enrolled)) 
  df_ss_clin <- df_res %>% 
    dplyr::summarise(ss_mean = mean(ss_clin), 
                     ss_sd = sd(ss_clin)) 
  df_ss_immu <- df_res %>% 
    dplyr::summarise(ss_mean = mean(ss_immu), 
                     ss_sd = sd(ss_immu)) 
  
  # probability of sample size
  ss_cut <- cut(df_res$n_enrolled, breaks = c(0, 250, 500, 750, 1000), 
                include.lowest = T, right = F)
  prob_ss <- prop.table(table(ss_cut))
  prob_ss <- as.numeric(cumsum(prob_ss))

  flab <- gsub("res-", "", fname)
  flab <- gsub('.RDS', "", flab)
  
  mydate <- as.POSIXlt(flab, format="%Y-%m-%d-%H-%M-%S")
  
  dtmp <- data.frame(idsim = d1$cfg$id_sim,
                     nsim = nsim,

                     basesero = basesero,
                     trtsero = trtsero,
                     baseclin = baseclin,
                     trtclin = trtclin,
                     accrual = accrual,
                     info_delay = info_delay,
                     
                     # probability of each decision over interims
                     prob_sup = prob["ES"],
                     prob_fut = prob["Fut"],
                     prob_sv = prob["SV"],
                     prob_nd = prob["ND"],
                     
                     # probability of success at final
                     prob_fin_immi = probimmi,
                     prob_fin_clin = probclin,

                     # overall mean ss for clin and immu
                     ss_enrlld_mean = as.numeric(df_ss_enrlld["ss_mean"]),
                     ss_enrlld_sd = as.numeric(df_ss_enrlld["ss_sd"]),
                     ss_immu_mean = as.numeric(df_ss_immu["ss_mean"]),
                     ss_immu_sd = as.numeric(df_ss_immu["ss_sd"]),
    
                     prob_ss_lt250 = as.numeric(prob_ss[1]),
                     prob_ss_lt500 = as.numeric(prob_ss[2]),
                     prob_ss_lt750 = as.numeric(prob_ss[3]),
                     prob_ss_lt1k = as.numeric(prob_ss[4]),
                     
                     fname = flab, stringsAsFactors = F, 
                     date = mydate,
    durn = as.numeric(d1$duration))
  
  # summary data
  dtmp <- dtmp %>%
    dplyr::mutate(f_prob_sup = sprintf("%.3f", prob_sup),
                  f_prob_fut = sprintf("%.3f", prob_fut),
                  f_prob_sv = sprintf("%.3f", prob_sv),
                  f_prob_nd = sprintf("%.3f", prob_nd),
                  
                  f_prob_fin_i = sprintf("%.3f", prob_fin_immi),
                  f_prob_fin_c = sprintf("%.3f", prob_fin_clin),
                  
                  f_ss_enrl = sprintf("%.0f (%.1f)", ss_enrlld_mean, ss_enrlld_sd),
                  f_ss_immu = sprintf("%.0f (%.1f)", ss_immu_mean, ss_immu_sd),

                  f_ss_lt1 = sprintf("%.2f", prob_ss_lt250),
                  f_ss_lt2 = sprintf("%.2f", prob_ss_lt500),
                  f_ss_lt3 = sprintf("%.2f", prob_ss_lt750),
                  f_ss_lt4 = sprintf("%.2f", prob_ss_lt1k)
                  )

  df_all <- rbind(df_all,  dtmp, stringsAsFactors  = F)
  

  df_res$mysim <- mysim
  mysim <- mysim + 1
  df_res_all <- rbind(df_res_all, df_res)

}

# unique(df_all$idsim)
df_0 <- df_all %>%
  dplyr::arrange(desc(fname)) %>%
  dplyr::mutate(row = 1:n()) %>%
  dplyr::select(baseclin, trtclin, basesero, trtsero, accrual,info_delay,
                f_prob_sup, f_prob_fut, f_prob_sv, f_prob_nd, 
                f_prob_fin_i, f_prob_fin_c,
                f_ss_enrl, f_ss_immu, 
                f_ss_lt1, f_ss_lt2, f_ss_lt3,
                nsim, durn, fname, idsim,  date, row)



options(knitr.kable.NA = '-')
showwarn <- length(mywarnings > 0)

#max_file_date <- as.POSIXct("2019-03-13 23:11:48")

```




```{r, echo = showwarn, eval=showwarn}
print("WARNINGS PRESENT IN DATA!!")
```


```{r, echo = F, eval = T}
digits <- c(0, 0, 2, 2, 
            0, 2,
            0, 0, 0, 0, 
            0, 0,
            0, 0, 
            0, 0, 0, 
            0, 2, 0, 0)

kable(df_0 %>% 
  dplyr::arrange(desc(fname)) %>%
    dplyr::mutate(d = trtclin - baseclin,
                  g = trtsero - basesero) %>%
    dplyr::filter(d != 0 & g!= 0) %>%
  dplyr::select(-date, -fname, -d, -g),
      caption = paste0("Table 6. Simulation Results (", nrow(df_0), " rows)"),
      col.names = c("ctl", "trt", "ctl", "trt", 
                    "accrual", "delay",
                    "e.s.", "e.f", "s.v.", "n.d", 
                    "p.clin", "p.immu",
                    "enrolled", "bloods", 
                    "P(<250)", "P(<500)", "P(<750)", 
                    "nsim", "durn.hr", "idsim", "row"),
      digits = digits) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F, position = "left",
                font_size = 12,
                latex_options = "hold_position") %>%
  add_header_above(c("Clinical" = 2, "Seroconversion" = 2, 
                     "Info rate" = 2, 
                     "Interim" = 4,
                     "Final" = 2,
                     "SS" = 5, 
                     " " = 4))

```


```{r, echo = F, eval = T}
digits <- c(0, 0, 2, 2, 
            0, 2,
            0, 0, 0, 0, 
            0, 0,
            0, 0, 
            0, 0, 0, 
            0, 2, 0, 0)

kable(df_0 %>% 
  dplyr::arrange(desc(fname)) %>%
    dplyr::mutate(d = trtclin - baseclin,
                  g = trtsero - basesero) %>%
    dplyr::filter(d == 0 & g == 0) %>%
  dplyr::select(-date, -fname, -d, -g),
      caption = paste0("Table 6. Null case results (", nrow(df_0), " rows)"),
      col.names = c("ctl", "trt", "ctl", "trt", 
                    "accrual", "delay",
                    "e.s.", "e.f", "s.v.", "n.d", 
                    "p.clin", "p.immu",
                    "enrolled", "bloods", 
                    "P(<250)", "P(<500)", "P(<750)", 
                    "nsim", "durn.hr", "idsim", "row"),
      digits = digits) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"),
                full_width = F, position = "left",
                font_size = 12,
                latex_options = "hold_position") %>%
  add_header_above(c("Clinical" = 2, "Seroconversion" = 2, 
                     "Info rate" = 2, 
                     "Interim" = 4,
                     "Final" = 2,
                     "SS" = 5, 
                     " " = 4))

```

# Figures


```{r, eval = F,  echo = F, fig.width=4, fig.height=4}
ggplot(df_res_all, aes(x = c_p_fin, group = paste0(mysim)))+
    geom_density()+
  ggtitle("Clinical - final posterior prob of trt success")
```

```{r, eval = F, echo = F, fig.width=4, fig.height=4}
ggplot(df_res_all, aes(x = c_ppmax, group = paste0(mysim)))+
    geom_density()+
  ggtitle("Clinical - final predictive prob at max")
```

```{r, eval = F, echo = F, fig.width=4, fig.height=4}
ggplot(df_res_all, aes(x = c_ppn, group = paste0(mysim)))+
    geom_density()+
  ggtitle("Clinical - predictive prob at interim")
```

```{r, eval = F, echo = F, fig.width=4, fig.height=4}
ggplot(df_res_all, aes(x = i_p_fin, group = paste0(mysim)))+
    geom_density()+
  ggtitle("Immunological - final posterior prob of trt success")
```

```{r, eval = F, echo = F, fig.width=4, fig.height=4}
ggplot(df_res_all, aes(x = i_ppmax, group = paste0(mysim)))+
    geom_density()+
  ggtitle("Immunological - final predictive prob at max")
```

```{r, eval = F, echo = F, fig.width=4, fig.height=4}
ggplot(df_res_all, aes(x = i_ppn, group = paste0(mysim)))+
    geom_density()+
  ggtitle("Immunological - predictive prob at interim")
```


